# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # Database Service (PostgreSQL)
  db:
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: notreddit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: notreddit-server # Use an image built from the specified dockerfile in the `notreddit-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8001:8000" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    env_file: server-variables.env
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend
    environment:
      - TZ=Europe/Sofia

  # Frontend Service 
  app-client:
    build:
      context: notreddit-client # Use an image built from the specified dockerfile in the `notreddit-client` directory.
      dockerfile: Dockerfile
    ports:
      - "3001:80" # Forward the exposed port 80 on the container to port 80 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend
    environment:
      - TZ=Europe/Sofia

# Volumes
volumes:
  db-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    