[build]
  base = "notreddit-client/"
  publish = "build/"
  command = "npm run build"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/api/*"
  to = "http://notreddit-env.fspzgqurca.us-east-1.elasticbeanstalk.com/api"
  status = 200